/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapturaTeclaC;

import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author USER
 */
public class VentanaPricipal extends javax.swing.JFrame {
    
    private DefaultListModel<String> modeloLista; // modelo dinámico

    public VentanaPricipal() {
        initComponents();   
        inicializarModelo(); //Se carga el modelo dinámico
        registrarEventos(); //Se capturan las teclas
        configurarBoton(); // accion del botón
    }
    // Inicializa la lista con un modelo dinámico
    private void inicializarModelo() {
        modeloLista = new DefaultListModel<>();
        modeloLista.addElement("Tema 1: Matemáticas");
        modeloLista.addElement("Tema 2: Programación");
        modeloLista.addElement("Tema 3: Física");
        modeloLista.addElement("Tema 4: Química");
        modeloLista.addElement("Tema 5: Sistemas");

        miLista.setModel(modeloLista); // asignamos el modelo al JList
    }
    // Captura la tecla "C" en la lista
    private void registrarEventos() {
        miLista.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar() == 'c' || e.getKeyChar() == 'C') {
                    int index = miLista.getSelectedIndex();
                    if (index != -1) {
                        String item = modeloLista.getElementAt(index);
                        System.out.println("Tecla 'C' presionada sobre: " + item);

                        // Alternar marcado con [X]
                        if (item.startsWith("[X] ")) {
                            modeloLista.set(index, item.substring(4));
                        } else {
                            modeloLista.set(index, "[X] " + item);
                        }
                    } else {
                        System.out.println("No hay ningún elemento seleccionado.");
                    }
                }
            }
        });
    }
    
    // Acción para el botón
    private void configurarBoton() {
        miBoton.addActionListener(e -> {
            int index = miLista.getSelectedIndex();
            if (index != -1) {
                JOptionPane.showMessageDialog(this, 
                    "Seleccionaste: " + modeloLista.getElementAt(index));
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No has seleccionado ningún elemento.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        miLista = new javax.swing.JList<>();
        miBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        miLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(miLista);

        miBoton.setText("Mostrar selección");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(miBoton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(miBoton)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton miBoton;
    private javax.swing.JList<String> miLista;
    // End of variables declaration//GEN-END:variables
}
